force-app/main/default/objects/LimitWatcherEvent__e/LimitWatcherEvent__e.object-meta.xml
<CustomObject>
    <description>Allows system limit monitoring to escape the execution context</description>
    <label>Limit Watcher Event</label>
    <pluralLabel>Limit Watcher Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/LimitWatcherEvent__e/fields/AggregateQueries__c.field-meta.xml
<CustomField>
    <fullName>AggregateQueries__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Aggregate Queries</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LimitWatcherEvent__e/fields/AsyncCalls__c.field-meta.xml
<CustomField>
    <fullName>AsyncCalls__c</fullName>
    <description>*** future use ***</description>
    <label>Async Calls</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LimitWatcherEvent__e/fields/CallContext__c.field-meta.xml
<CustomField>
    <fullName>CallContext__c</fullName>
    <description>The call context (calling class, entry point)</description>
    <label>Call Context</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LimitWatcherEvent__e/fields/Callouts__c.field-meta.xml
<CustomField>
    <fullName>Callouts__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Callouts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LimitWatcherEvent__e/fields/FutureCalls__c.field-meta.xml
<CustomField>
    <fullName>FutureCalls__c</fullName>
    <label>Future Calls</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LimitWatcherEvent__e/fields/isPersisted__c.field-meta.xml
<CustomField>
    <fullName>isPersisted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether the record should be stored in the database</description>
    <label>Persist to Database</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LimitWatcherEvent__e/fields/PublishImmediateDML__c.field-meta.xml
<CustomField>
    <fullName>PublishImmediateDML__c</fullName>
    <label>Publish Immediate DML</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LimitWatcherEvent__e/fields/Queries__c.field-meta.xml
<CustomField>
    <fullName>Queries__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Queries</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LimitWatcherEvent__e/fields/QueryRows__c.field-meta.xml
<CustomField>
    <fullName>QueryRows__c</fullName>
    <label>Query Rows</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LimitWatcherEvent__e/fields/QueueableJobs__c.field-meta.xml
<CustomField>
    <fullName>QueueableJobs__c</fullName>
    <label>Queueable Jobs</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LimitWatcherEvent__e/fields/Quiddity__c.field-meta.xml
<CustomField>
    <fullName>Quiddity__c</fullName>
    <label>Quiddity</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LimitWatcherEvent__e/fields/SnapshotLabel__c.field-meta.xml
<CustomField>
    <fullName>SnapshotLabel__c</fullName>
    <description>A label for the snapshot.</description>
    <label>Snapshot Label</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LimitWatcherEvent__e/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LimitWatcherLog__c/LimitWatcherLog__c.object-meta.xml
<CustomObject>
    <description>System limit monitoring log entries</description>
    <label>Limit Watcher Log Entry</label>
    <nameField>
        <displayFormat>LIMIT-{0000000}</displayFormat>
        <label>Limit Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Limit Watcher Log Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LimitWatcherLog__c/fields/AggregateQueries__c.field-meta.xml
<CustomField>
    <fullName>AggregateQueries__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Aggregate Queries</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LimitWatcherLog__c/fields/AsyncCalls__c.field-meta.xml
<CustomField>
    <fullName>AsyncCalls__c</fullName>
    <description>*** future use ***</description>
    <label>Async Calls</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LimitWatcherLog__c/fields/CallContext__c.field-meta.xml
<CustomField>
    <fullName>CallContext__c</fullName>
    <description>The call context (calling class, entry point)</description>
    <label>Call Context</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LimitWatcherLog__c/fields/Callouts__c.field-meta.xml
<CustomField>
    <fullName>Callouts__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Callouts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LimitWatcherLog__c/fields/CpuTime__c.field-meta.xml
<CustomField>
    <fullName>CpuTime__c</fullName>
    <label>CPU Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LimitWatcherLog__c/fields/DMLRows__c.field-meta.xml
<CustomField>
    <fullName>DMLRows__c</fullName>
    <defaultValue>0</defaultValue>
    <label>DML Rows</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LimitWatcherLog__c/fields/DMLStatements__c.field-meta.xml
<CustomField>
    <fullName>DMLStatements__c</fullName>
    <defaultValue>0</defaultValue>
    <label>DML Statements</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LimitWatcherLog__c/fields/EmailInvocations__c.field-meta.xml
<CustomField>
    <fullName>EmailInvocations__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Email Invocations</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LimitWatcherLog__c/fields/FutureCalls__c.field-meta.xml
<CustomField>
    <fullName>FutureCalls__c</fullName>
    <label>Future Calls</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LimitWatcherLog__c/fields/HeapSize__c.field-meta.xml
<CustomField>
    <fullName>HeapSize__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Heap Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LimitWatcherLog__c/fields/isPersisted__c.field-meta.xml
<CustomField>
    <fullName>isPersisted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether the record should be stored in the database</description>
    <label>Persist to Database</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LimitWatcherLog__c/fields/MobilePushApexCalls__c.field-meta.xml
<CustomField>
    <fullName>MobilePushApexCalls__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Mobile Push Apex Calls</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LimitWatcherLog__c/fields/OperationType__c.field-meta.xml
<CustomField>
    <fullName>OperationType__c</fullName>
    <label>Operation Type</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LimitWatcherLog__c/fields/PublishImmediateDML__c.field-meta.xml
<CustomField>
    <fullName>PublishImmediateDML__c</fullName>
    <label>Publish Immediate DML</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LimitWatcherLog__c/fields/Queries__c.field-meta.xml
<CustomField>
    <fullName>Queries__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Queries</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LimitWatcherLog__c/fields/QueryLocatorRows__c.field-meta.xml
<CustomField>
    <fullName>QueryLocatorRows__c</fullName>
    <label>Query Locator Rows</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LimitWatcherLog__c/fields/QueryRows__c.field-meta.xml
<CustomField>
    <fullName>QueryRows__c</fullName>
    <label>Query Rows</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LimitWatcherLog__c/fields/QueueableJobs__c.field-meta.xml
<CustomField>
    <fullName>QueueableJobs__c</fullName>
    <label>Queueable Jobs</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LimitWatcherLog__c/fields/SnapshotLabel__c.field-meta.xml
<CustomField>
    <fullName>SnapshotLabel__c</fullName>
    <description>A label for the snapshot.</description>
    <label>Snapshot Label</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LimitWatcherLog__c/fields/SoslQueries__c.field-meta.xml
<CustomField>
    <fullName>SoslQueries__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SOSLQueries</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LimitWatcherLog__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LimitsWatcher.cls
public class LimitsWatcher {
    
    public static String caller;
    public static String snapshotLabel;
    
    public static void snapshot() {
        snapshot(false);
    }
    
    public static void snapshot(Boolean persist) {
        
        Request reqInfo = Request.getCurrent();
 		LimitWatcherEvent__e event = getEvent(persist);
        event.Transaction__c = reqInfo.getRequestId();
		event.Quiddity__c = String.valueOf(reqInfo.getQuiddity());        
        
        if (System.Limits.getLimitPublishImmediateDML() - System.Limits.getPublishImmediateDML() == 1 ) {
            event.isPersisted__c = true;
        }
        
        EventBus.publish(event);
    }
    
    public static void doPersist(List<LimitWatcherEvent__e> events) {
        
        List<LimitWatcherLog__c> logEntries = new List<LimitWatcherLog__c>();
            
            for (LimitWatcherEvent__e ev : events) {
                
                if (!ev.isPersisted__c) {
                    continue;
                }
                
                logEntries.add(createSObject(ev));
            }
        
        insert logEntries;
        
    }
    
    private static LimitWatcherEvent__e getEvent(Boolean persist) {
        
        return new LimitWatcherEvent__e(
            AggregateQueries__c	= System.Limits.getAggregateQueries(),
			AsyncCalls__c = System.Limits.getAsyncCalls(),
			CallContext__c = caller,
			Callouts__c	= System.Limits.getCallouts(),
			CpuTime__c	= System.Limits.getCpuTime(),
			DMLRows__c = System.Limits.getDMLRows(),
			DMLStatements__c = System.Limits.getDMLStatements(), 
			EmailInvocations__c = System.Limits.getEmailInvocations(),
            FutureCalls__c = System.Limits.getFutureCalls(),
            HeapSize__c = System.Limits.getHeapSize(),
            MobilePushApexCalls__c = System.Limits.getMobilePushApexCalls(),
            isPersisted__c = persist,
            PublishImmediateDML__c = System.Limits.getPublishImmediateDML(),
            Queries__c	= System.Limits.getQueries(),
            QueryLocatorRows__c	= System.Limits.getQueryLocatorRows(),
            QueryRows__c = System.Limits.getQueryRows(),
            QueueableJobs__c = System.Limits.getQueueableJobs(),
            Quiddity__c = '',
            SnapshotLabel__c = snapshotLabel,
            SoslQueries__c = System.Limits.getSoslQueries(),
            Transaction__c = ''
       );
    }
    
    private static LimitWatcherLog__c createSObject(LimitWatcherEvent__e ev) {
        
        return new LimitWatcherLog__c(
            AggregateQueries__c	= ev.AggregateQueries__c,
            AsyncCalls__c = ev.AsyncCalls__c,
			CallContext__c = ev.CallContext__c,
			Callouts__c	= ev.Callouts__c,
			CpuTime__c	= ev.CpuTime__c,
			DMLRows__c = ev.DMLRows__c,
			DMLStatements__c = ev.DMLStatements__c, 
			EmailInvocations__c = ev.EmailInvocations__c,
            FutureCalls__c = ev.FutureCalls__c,
            HeapSize__c = ev.HeapSize__c,
            MobilePushApexCalls__c = ev.MobilePushApexCalls__c,
            PublishImmediateDML__c = ev.PublishImmediateDML__c,
            Queries__c	= ev.Queries__c,
            QueryLocatorRows__c	= ev.QueryLocatorRows__c,
            QueryRows__c = ev.QueryRows__c,
            QueueableJobs__c = ev.QueueableJobs__c,
            OperationType__c = ev.Quiddity__c,
            SnapshotLabel__c = ev.SnapshotLabel__c,
            SoslQueries__c = ev.SoslQueries__c,
            Transaction__c = ev.Transaction__c
        );
    }
    
}